### ISSUE TITLE
Some elements still in Spanish

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro.github.io-source#3]
See for instance http://poliastro.github.io/author/antonio-hidalgo-galindo.html

**Comment by anhiga** [comment]
This commit e6cdb257f82aa39e37e11ec9ca0d7a807f782b72 translates some more strings. Issue can remain opened just in case, though.

**Comment by Juanlu001** [comment]
I think this can be closed now, but I'm opening a related issue.
